# Generated by Django 2.2.5 on 2020-04-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200420_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='order_no',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
