# Generated by Django 2.2.5 on 2020-05-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_answer_explanation'),
        ('course', '0003_module_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
    ]
