# Generated by Django 2.2.5 on 2020-06-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_module_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
