# Generated by Django 2.2.5 on 2020-03-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20191227_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct_bool',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
