# Generated by Django 2.2.5 on 2020-04-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_answer_correct_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='explanation',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
