# Generated by Django 2.2.5 on 2020-07-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_passing_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='opic',
            field=models.TextField(default='Unclassified'),
        ),
    ]
