# Generated by Django 2.2.5 on 2020-04-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0013_auto_20200411_2123'),
        ('navquiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='NavAnswer',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='NavQuestion',
        ),
    ]
