# Generated by Django 2.2.5 on 2020-04-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navquiz', '0002_auto_20200411_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navanswer',
            name='mpep_location',
            field=models.CharField(max_length=50),
        ),
    ]
