# Generated by Django 2.2.5 on 2019-12-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
