# Generated by Django 2.2.5 on 2020-04-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_answerssubmitted_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='score',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
            preserve_default=False,
        ),
    ]
