# Generated by Django 2.2.5 on 2020-04-06 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0008_quizattempt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='time_bob',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
