# Generated by Django 2.2.5 on 2020-04-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0010_auto_20200406_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='submitted_bool',
            field=models.BooleanField(default=False),
        ),
    ]
