# Generated by Django 2.2.5 on 2020-04-11 20:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_answer_correct_bool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userProfile', '0011_quizattempt_submitted_bool'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavQuizAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_taken', models.DurationField(default=datetime.timedelta(0))),
                ('submitted_bool', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NavAnswersSubmitted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField()),
                ('time_taken', models.DurationField(default=datetime.timedelta(0))),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Answer')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.QuizAttempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
