# Generated by Django 2.2.5 on 2020-04-11 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0012_navanswerssubmitted_navquizattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navanswerssubmitted',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.NavQuizAttempt'),
        ),
    ]
