# Generated by Django 2.2.5 on 2020-04-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0014_auto_20200411_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navanswerssubmitted',
            name='article_submitted',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
