# Generated by Django 2.2.5 on 2020-04-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0016_auto_20200412_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='navanswerssubmitted',
            name='correct_bool',
            field=models.BooleanField(default=False),
        ),
    ]
