# Generated by Django 2.2.5 on 2020-04-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0017_navanswerssubmitted_correct_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navanswerssubmitted',
            name='article_submitted',
            field=models.CharField(max_length=50),
        ),
    ]
