# Generated by Django 2.2.5 on 2020-04-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0018_auto_20200416_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='navanswerssubmitted',
            name='submitted_bool',
            field=models.BooleanField(default=False),
        ),
    ]
