# Generated by Django 2.2.5 on 2020-04-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0019_navanswerssubmitted_submitted_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='navquizattempt',
            name='user_attempt_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
