# Generated by Django 2.2.5 on 2020-04-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0020_navquizattempt_user_attempt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='user_attempt_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
